# zsh config base file. Source at the top of your .zshrc

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Another reminder to manipulate $PATH in .zprofile and not here.
# See README for why.

# Set man pager to nvim
export MANPAGER="nvim +Man!"

# Directory containing this file
SRC_DIR=${${(%):-%x}:A:h}

# Increase the size of shell history stored in $HISTFILE.
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/history"
export HISTSIZE=100000
export SAVEHIST=100000
# History deduplication options
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS

# Set theme and config
ZSH_THEME="powerlevel10k/powerlevel10k"
source "$SRC_DIR/omz-config.zsh"

# Invoke oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit p10k.zsh.
[[ ! -f $SRC_DIR/p10k.zsh ]] || source $SRC_DIR/p10k.zsh

# Set theme for zsh fast-syntax-highlighting
fast-theme -q XDG:catppuccin-mocha

# Optimize autosuggestions for better performance and quality
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
export ZSH_AUTOSUGGEST_USE_ASYNC=true
# Disable autosuggestions during paste to improve paste performance
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic
}
pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

# Setup completions
eval "$(zoxide init zsh)"

# Configure fzf to use zoxide for Alt+C directory navigation
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"
export FZF_ALT_C_OPTS="--preview 'lsd --tree --depth 2 --color=always {}'"

# FZF default options with Catppuccin Mocha theme (transparent background)
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border --inline-info \
  --color=bg+:-1,spinner:#f5e0dc,hl:#f38ba8 \
  --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
  --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

# Avoid conflicts in fzf completion and zsh-vi-mode
# Also override fzf-cd-widget after fzf initialization to use zoxide
zvm_after_init_commands+=(
  'source <(fzf --zsh)'
  'fzf-cd-widget-with-zoxide() {
    local dir
    dir=$(eval "$FZF_ALT_C_COMMAND" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse --bind=ctrl-z:ignore ${FZF_DEFAULT_OPTS-} ${FZF_ALT_C_OPTS-}" $(__fzfcmd) +m)
    if [[ -n "$dir" ]]; then
      BUFFER="z ${(q)dir}"
      zle accept-line
    fi
    zle reset-prompt
  }
  zle -N fzf-cd-widget-with-zoxide
  bindkey '\''\ec'\'' fzf-cd-widget-with-zoxide'
)

# Setup aliases
alias ls="lsd"
alias h="head -n" # Useful for $ some_command | h 10

