# zsh config base file. Source at the top of your .zshrc

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Another reminder to manipulate $PATH in .zprofile and not here.
# See README for why.

# Directory containing this file
SRC_DIR=${${(%):-%x}:A:h}

# Increase the size of shell history stored in $HISTFILE.
export HISTSIZE=100000
export SAVEHIST=100000

# Set theme and config
ZSH_THEME="powerlevel10k/powerlevel10k"
source "$SRC_DIR/omz-config.zsh"

# Invoke oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit p10k.zsh.
[[ ! -f $SRC_DIR/p10k.zsh ]] || source $SRC_DIR/p10k.zsh

# Set theme for zsh fast-syntax-highlighting
fast-theme -q XDG:catppuccin-mocha

# Setup completions
eval "$(zoxide init zsh)"
# Avoid conflicts in fzf completion and zsh-vi-mode
zvm_after_init_commands+=('source <(fzf --zsh)')

# Setup aliases
alias ls="lsd"

